version: "3.8"

services:
  api:
    container_name: noterest-auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-auth.rule=PathPrefix(`/auth/{[a-z]+}`)"
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      bash -c "
      uvicorn app.main:app --reload-dir ./app --host 0.0.0.0 --port 8000 --debug "
